import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import ejs from 'ejs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TEMPLATES_DIR = join(__dirname, '..', 'templates')

export async function renderTemplate(
  templateName: string,
  data: Record<string, unknown>,
): Promise<string> {
  const templatePath = join(TEMPLATES_DIR, templateName)
  const template = await readFile(templatePath, 'utf8')
  return ejs.render(template, data, { async: false }) as string
}

export const GENERATED_HEADER = `# Generated by fabis-ralph-loop — DO NOT EDIT MANUALLY
# Regenerate with: npx fabis-ralph-loop generate
`
