import { readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import ejs from 'ejs'

/**
 * Resolve a bundled asset directory (templates, static, uac-templates).
 * In dist (flat layout): assets are siblings of the compiled files.
 * In src (nested layout via tsx): assets are siblings of the parent dir.
 */
export function resolveAssetDir(assetName: string, metaUrl: string): string {
  const dir = dirname(fileURLToPath(metaUrl))
  const sibling = join(dir, assetName)
  if (existsSync(sibling)) return sibling
  return join(dir, '..', assetName)
}

const TEMPLATES_DIR = resolveAssetDir('templates', import.meta.url)

export async function renderTemplate(
  templateName: string,
  data: Record<string, unknown>,
): Promise<string> {
  const templatePath = join(TEMPLATES_DIR, templateName)
  const template = await readFile(templatePath, 'utf8')
  return ejs.render(template, data, { async: false, escape: (s: string) => s }) as string
}

export const GENERATED_HEADER = `# Generated by fabis-ralph-loop — DO NOT EDIT MANUALLY
# Regenerate with: npx fabis-ralph-loop generate
`
