import { describe, it, expect } from 'vitest'
import { generateDockerfile } from '../../src/generators/dockerfile.js'
import { makeConfig } from '../helpers/make-config.js'

describe('generateDockerfile', () => {
  it('generates a basic Dockerfile with node base image', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('FROM node:22-bookworm')
    expect(result).toContain('vim')
    expect(result).toContain('direnv')
    expect(result).toContain('claude.ai/install.sh')
    expect(result).toContain('ENTRYPOINT')
    expect(result).toContain('entrypoint.ts')
    // Should NOT install Node separately for node base
    expect(result).not.toContain('nodesource')
    expect(result).not.toContain('chromium')
  })

  it('installs Node for non-node base images', async () => {
    const config = makeConfig({
      container: { name: 'test', baseImage: 'python:3.12-bookworm' },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('FROM python:3.12-bookworm')
    expect(result).toContain('nodesource')
  })

  it('includes Playwright/Chromium when enabled', async () => {
    const config = makeConfig({
      container: { name: 'test', playwright: true },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('chromium')
    expect(result).toContain('fonts-liberation')
    expect(result).toContain('PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH')
    expect(result).toContain('@playwright/mcp')
  })

  it('includes extra system packages', async () => {
    const config = makeConfig({
      container: { name: 'test', systemPackages: ['postgresql-client', 'redis-tools'] },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('postgresql-client')
    expect(result).toContain('redis-tools')
  })

  it('includes rootSetup hooks', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        hooks: {
          rootSetup: ['RUN npm install -g pnpm@10'],
        },
      },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('RUN npm install -g pnpm@10')
  })

  it('includes userSetup hooks', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        hooks: {
          userSetup: ['RUN corepack enable'],
        },
      },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('RUN corepack enable')
    // userSetup should appear after USER sandbox
    const userIdx = result.indexOf('USER sandbox')
    const hookIdx = result.indexOf('RUN corepack enable')
    expect(hookIdx).toBeGreaterThan(userIdx)
  })

  it('creates sandbox user with UID 1000 by default', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('groupadd -g 1000 sandbox')
    expect(result).toContain('useradd -m -u 1000 -g 1000')
    expect(result).toContain('USER sandbox')
    expect(result).toContain('/home/sandbox/.claude')
  })

  it('reuses existing user when container.user is set', async () => {
    const config = makeConfig({
      container: { name: 'test', user: 'node' },
    })
    const result = await generateDockerfile(config)

    expect(result).not.toContain('groupadd')
    expect(result).not.toContain('useradd')
    expect(result).toContain('USER node')
    expect(result).toContain('/home/node/.claude')
    expect(result).toContain('node ALL=(ALL) NOPASSWD:ALL')
  })

  it('errors clearly when UID 1000 is taken during sandbox creation', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('Set container.user')
    expect(result).toContain('fabis-ralph-loop.config.ts')
  })

  it('includes run-fabis-ralph-loop wrapper script', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('run-fabis-ralph-loop')
    expect(result).toContain('npx --yes fabis-ralph-loop@')
    expect(result).toContain('/usr/local/bin/run-fabis-ralph-loop')
  })

  it('includes generated header', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('Generated by fabis-ralph-loop')
  })
})
