import { describe, it, expect } from 'vitest'
import { ralphLoopConfigSchema } from '../../src/config/schema.js'
import { applyPlaywrightDefaults } from '../../src/config/defaults.js'
import { generateDockerfile } from '../../src/generators/dockerfile.js'

function makeConfig(overrides: Record<string, unknown> = {}) {
  return applyPlaywrightDefaults(
    ralphLoopConfigSchema.parse({
      project: { name: 'Test' },
      ...overrides,
    }),
  )
}

describe('generateDockerfile', () => {
  it('generates a basic Dockerfile with node base image', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('FROM node:22-bookworm')
    expect(result).toContain('vim')
    expect(result).toContain('direnv')
    expect(result).toContain('claude.ai/install.sh')
    expect(result).toContain('ENTRYPOINT')
    expect(result).toContain('entrypoint.ts')
    // Should NOT install Node separately for node base
    expect(result).not.toContain('nodesource')
    expect(result).not.toContain('chromium')
  })

  it('installs Node for non-node base images', async () => {
    const config = makeConfig({
      container: { name: 'test', baseImage: 'python:3.12-bookworm' },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('FROM python:3.12-bookworm')
    expect(result).toContain('nodesource')
  })

  it('includes Playwright/Chromium when enabled', async () => {
    const config = makeConfig({
      container: { name: 'test', playwright: true },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('chromium')
    expect(result).toContain('fonts-liberation')
    expect(result).toContain('PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH')
    expect(result).toContain('@playwright/mcp')
  })

  it('includes extra system packages', async () => {
    const config = makeConfig({
      container: { name: 'test', systemPackages: ['postgresql-client', 'redis-tools'] },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('postgresql-client')
    expect(result).toContain('redis-tools')
  })

  it('includes rootSetup hooks', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        hooks: {
          rootSetup: ['RUN npm install -g pnpm@10'],
        },
      },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('RUN npm install -g pnpm@10')
  })

  it('includes userSetup hooks', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        hooks: {
          userSetup: ['RUN corepack enable'],
        },
      },
    })
    const result = await generateDockerfile(config)

    expect(result).toContain('RUN corepack enable')
    // userSetup should appear after USER node
    const userNodeIdx = result.indexOf('USER node')
    const hookIdx = result.indexOf('RUN corepack enable')
    expect(hookIdx).toBeGreaterThan(userNodeIdx)
  })

  it('includes generated header', async () => {
    const config = makeConfig()
    const result = await generateDockerfile(config)

    expect(result).toContain('Generated by fabis-ralph-loop')
  })
})
