import { describe, it, expect } from 'vitest'
import { generateEntrypoint } from '../../src/generators/entrypoint.js'
import { makeConfig } from '../helpers/make-config.js'

describe('generateEntrypoint', () => {
  it('generates entrypoint with default config', async () => {
    const config = makeConfig()
    const result = await generateEntrypoint(config)

    expect(result).toContain('Generated by fabis-ralph-loop')
    expect(result).toContain("const agent = 'claude'")
    expect(result).toContain('const shadowVolumes: string[] = []')
    expect(result).not.toContain('entrypointSetupCommands')
  })

  it('bakes in shadow volumes', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        shadowVolumes: ['/workspace/node_modules', '/workspace/packages/app/node_modules'],
      },
    })
    const result = await generateEntrypoint(config)

    expect(result).toContain(
      'const shadowVolumes: string[] = ["/workspace/node_modules","/workspace/packages/app/node_modules"]',
    )
  })

  it('includes entrypoint setup commands when configured', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        hooks: {
          entrypointSetup: ['pnpm install --frozen-lockfile', 'pnpm db:migrate'],
        },
      },
    })
    const result = await generateEntrypoint(config)

    expect(result).toContain('entrypointSetupCommands')
    expect(result).toContain('pnpm install --frozen-lockfile')
    expect(result).toContain('pnpm db:migrate')
  })

  it('omits entrypoint setup section when no commands', async () => {
    const config = makeConfig()
    const result = await generateEntrypoint(config)

    expect(result).not.toContain('Entrypoint setup commands')
    expect(result).not.toContain('entrypointSetupCommands')
  })

  it('does not read config from env vars', async () => {
    const config = makeConfig()
    const result = await generateEntrypoint(config)

    expect(result).not.toContain('process.env.RALPH_AGENT')
    expect(result).not.toContain('process.env.RALPH_SHADOW_VOLUMES')
  })

  it('includes SSL cert trust section when sslCerts is set', async () => {
    const config = makeConfig({
      container: { name: 'test', sslCerts: '.certs' },
    })
    const result = await generateEntrypoint(config)

    expect(result).toContain('SSL Certificate Trust')
    expect(result).toContain('update-ca-certificates')
    expect(result).toContain('NODE_EXTRA_CA_CERTS')
    expect(result).not.toContain('certutil')
  })

  it('includes Chromium NSS setup when sslCerts and playwright are both set', async () => {
    const config = makeConfig({
      container: { name: 'test', sslCerts: '.certs', playwright: true },
    })
    const result = await generateEntrypoint(config)

    expect(result).toContain('SSL Certificate Trust')
    expect(result).toContain('update-ca-certificates')
    expect(result).toContain('certutil')
    expect(result).toContain('Chromium NSS')
  })

  it('omits SSL cert trust section when sslCerts is not set', async () => {
    const config = makeConfig()
    const result = await generateEntrypoint(config)

    expect(result).not.toContain('SSL Certificate Trust')
    expect(result).not.toContain('update-ca-certificates')
  })

  it('uses configured user for chown commands', async () => {
    const config = makeConfig({
      container: {
        name: 'test',
        user: 'node',
        shadowVolumes: ['/workspace/node_modules'],
      },
    })
    const result = await generateEntrypoint(config)

    expect(result).toContain('chown -R node:node')
    expect(result).not.toContain('sandbox:sandbox')
  })
})
