import { describe, it, expect } from 'vitest'
import { generatePrompt } from '../../src/generators/prompt.js'
import { makeConfig as _makeConfig } from '../helpers/make-config.js'

function makeConfig(overrides: Record<string, unknown> = {}) {
  return _makeConfig({ project: { name: 'Test Project' }, ...overrides })
}

describe('generatePrompt', () => {
  it('includes project name', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).toContain('Test Project')
  })

  it('includes project description when set', async () => {
    const config = makeConfig({
      project: { name: 'Test', description: 'A mood journaling app' },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('A mood journaling app')
  })

  it('includes project context', async () => {
    const config = makeConfig({
      project: { name: 'Test', context: 'Monorepo managed with pnpm 10' },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('Monorepo managed with pnpm 10')
  })

  it('includes backpressure commands', async () => {
    const config = makeConfig({
      project: {
        name: 'Test',
        backpressureCommands: [
          { name: 'Build shared', command: 'pnpm --filter @test/shared build' },
          { name: 'Lint', command: 'pnpm lint' },
        ],
      },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('# Build shared')
    expect(result).toContain('pnpm --filter @test/shared build')
    expect(result).toContain('# Lint')
    expect(result).toContain('pnpm lint')
  })

  it('does not HTML-escape special characters in commands', async () => {
    const config = makeConfig({
      project: {
        name: 'Test',
        backpressureCommands: [
          { name: 'Typecheck server', command: 'cd packages/server && yarn lint:tsc' },
        ],
        context: "Use logger.info({ err }, 'message') style",
      },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('cd packages/server && yarn lint:tsc')
    expect(result).not.toContain('&amp;')
    expect(result).toContain("logger.info({ err }, 'message')")
    expect(result).not.toContain('&#39;')
  })

  it('shows discovery fallback when no backpressure commands', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).toContain('Discover and run')
    expect(result).not.toContain('```bash')
  })

  it('includes completion signal', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).toContain('RALPH_WORK_FULLY_DONE')
  })

  it('uses custom completion signal', async () => {
    const config = makeConfig({
      defaults: { completionSignal: 'ALL_DONE' },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('ALL_DONE')
  })

  it('includes Playwright browser testing section when enabled', async () => {
    const config = makeConfig({
      container: { name: 'test', playwright: true },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('Playwright MCP')
    expect(result).toContain('headless Chromium')
  })

  it('omits Playwright section when disabled and no openAppSkill', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).not.toContain('Playwright MCP')
    expect(result).not.toContain('Browser Testing')
  })

  it('references openAppSkill when set', async () => {
    const config = makeConfig({
      project: { name: 'Test', openAppSkill: '.claude/skills/open-app/SKILL.md' },
    })
    const result = await generatePrompt(config)

    expect(result).toContain('.claude/skills/open-app/SKILL.md')
  })

  it('includes one-story-per-session constraint', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).toContain('ONE user story')
    expect(result).toContain('STOP')
  })

  it('includes generated header', async () => {
    const config = makeConfig()
    const result = await generatePrompt(config)

    expect(result).toContain('Generated by fabis-ralph-loop')
  })
})
